#!/usr/bin/env bash
# a Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009

# Display lines containing the word "bash" in the process list
ps -e | grep bash

