#!/usr/bin/env bash
# a function that display that performs a check on a function to see if
# it empty,it exist or is it a regular file 

file_name="school"

if [ -e "$file_name" ]; then
	echo "school file exists"
	if [ -s "$file_name" ]; then
		echo "school file not empty"
	else 
		echo "school file empty"
	fi
	if [ -f "$file_name" ]; then
		echo "school is a regular file"
	fi
		
else
	echo "school file exist does not exist"
fi
